Fix support for clang
Clang doesn't have the externally_visible attribute.

Fixes:
 alsa-lib//src/pcm/pcm.c:1503:1: error: unknown attribute 'externally_visible' ignored [-Werror,-Wunknown-attributes]
 EXPORT_SYMBOL snd_pcm_sframes_t INTERNAL(snd_pcm_forward)(snd_pcm_t *pcm, snd_pcm_uframes_t frames)
 ^
 alsa-lib/include/alsa-symbols.h:37:60: note: expanded from macro 'EXPORT_SYMBOL'
 #define EXPORT_SYMBOL __attribute__((visibility("default"),externally_visible))
                                                            ^

 ...
 fatal error: too many errors emitted, stopping now [-ferror-limit=]
 20 errors generated.

Signed-off-by: Chih-Wei Huang <cwhuang@linux.org.tw>