Fix an infinite recursive call
The function snd_ctl_remap_async will call itself infinitely. Looks like
a typo. Clang complains:

alsa-lib/src/control/control_remap.c:324:1: error: all paths through this function will call itself [-Werror,-Winfinite-recursion]
{
^
1 error generated.

Fixes: a64391a42 ("control: remap plugin - initial version")
Signed-off-by: Chih-Wei Huang <cwhuang@linux.org.tw>